name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install deps
        run: npm ci --prefer-offline

      - name: Check version change
        id: check
        uses: EndBug/version-check@v1

      - name: Create tag
        if: steps.check.outputs.changed == 'true'
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.check.outputs.version }}

      - uses: JS-DevTools/npm-publish@v3
        if: steps.check.outputs.changed == 'true'
        with:
          token: ${{ secrets.NPM_TOKEN }}
